In [14]:
import pandas as pd

data = {
"Rainfall_mm": [180, 190, 200, 210, 220],
"Yield_kg": [3000, 3100, 3200, 3400, 3500],
"fertilizer_kg": [40,45,50,55,60]
}

df = pd.DataFrame(data)

In [26]:
from sklearn.linear_model import LinearRegression

X = df[["Rainfall_mm"]] # Input: rainfall
y = df["Yield_kg"] # Output: yield

model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [21]:
# Predict yield for 205 mm rainfall
model.predict([[205]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7270.])

In [27]:
model.coef_, model.intercept_

(array([13.]), np.float64(640.0))

In [22]:
X = df[["Rainfall_mm", "Fertilizer_kg"]]
y = df["Yield_kg"]

model = LinearRegression()
model.fit(X, y)


KeyError: "['Fertilizer_kg'] not in index"

In [10]:
model.coef_

array([13.])